TEXT_TYPE_TEXT = "text"
TEXT_TYPE_BOLD = "bold"
TEXT_TYPE_ITALIC = "italic"
TEXT_TYPE_CODE = "code"
TEXT_TYPE_LINK = "link"
TEXT_TYPE_IMAGE = "image"
MD_TYPE_P = "paragraph"
MD_TYPE_H = "heading"
MD_TYPE_CODE = "code"
MD_TYPE_QUOTE = "quote"
MD_TYPE_UL = "unordered_list"
MD_TYPE_OL = "ordered_list"

